package com.example.Selenium_Idea;// Generated by Selenium IDE
import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.WebDriverRunner.getWebDriver;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import com.codeborne.selenide.Configuration;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DevopsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    /*
    FirefoxOptions options = new FirefoxOptions();
    options.setHeadless(true);
    driver = new FirefoxDriver(options);
     */

    Configuration.startMaximized = true;
    open("about:blank");
    driver = getWebDriver();

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void devopsTest() {
    driver.get("https://www.google.com/");
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector("#introAgreeButton")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.name("q")).sendKeys("Devops");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,388)");
    WebElement firstResult = new WebDriverWait(driver,10)
            .until(ExpectedConditions.elementToBeClickable(By.xpath("//span[contains(.,\'Qué es DevOps (y sobre todo qué no es DevOps) - Paradigma\')]")));
    driver.findElement(By.xpath("//span[contains(.,\'Qué es DevOps (y sobre todo qué no es DevOps) - Paradigma\')]")).click();
  }
}
