package com.example.Selenium_Idea;// Generated by Selenium IDE

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.WebDriverRunner.getWebDriver;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import com.codeborne.selenide.Configuration;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import static org.junit.Assert.*;

import java.util.*;

public class RoboTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
/*
    FirefoxOptions options = new FirefoxOptions();
    options.setHeadless(true);
    driver = new FirefoxDriver(options);
*/
    Configuration.startMaximized = true;
    open("about:blank");
    driver = getWebDriver();

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }


  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void RoboTest() {
    driver.get("http://localhost:3000/#!/");
    //driver.manage().window().setSize(new Dimension(980, 706));
    WebElement inicio1 = new WebDriverWait(driver,10)
            .until(ExpectedConditions.elementToBeClickable(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")));
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    vars.put("total1", driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText());
    assertEquals(vars.get("total1").toString(), "€8.25");
    driver.findElement(By.cssSelector(".btn-success")).click();
    //js.executeScript("window.scrollTo(0,0)");
    WebElement edad = new WebDriverWait(driver,10)
            .until(ExpectedConditions.elementToBeClickable(By.id("ageInput")));
    driver.findElement(By.id("ageInput")).sendKeys("22");
    driver.findElement(By.cssSelector(".btn-success")).click();
    WebElement compranueva = new WebDriverWait(driver,10)
            .until(ExpectedConditions.elementToBeClickable(By.linkText("New order")));
    vars.put("drinks", driver.findElement(By.cssSelector(".display-4")).getText());
    assertEquals(vars.get("drinks").toString(), "4 drinks");
    driver.findElement(By.linkText("New order")).click();
    WebElement inicio2 = new WebDriverWait(driver,10)
            .until(ExpectedConditions.elementToBeClickable(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")));
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    vars.put("total2", driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText());
    assertEquals(vars.get("total2").toString(), "€3.75");

    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    vars.put("drinks", driver.findElement(By.cssSelector(".display-4")).getText());
    assertEquals(vars.get("drinks").toString(), "3 drinks");
  }
}
